const fs = require("fs");
const path = require("path");

const root = __dirname;
const sourcePath = path.join(root, "main-source.cjs");
const corePath = path.join(root, "sync-core.cjs");
const outputPath = path.join(root, "main.js");

const source = fs.readFileSync(sourcePath, "utf8");
const core = fs.readFileSync(corePath, "utf8");

const exportStart = core.indexOf("\nmodule.exports = {");
if (exportStart === -1) {
  throw new Error("sync-core.cjs export block was not found.");
}

const coreForBundle = core.slice(0, exportStart).trim();
const syncRequirePattern = /const \{\r?\n[\s\S]*?\r?\n\} = require\("\.\/sync-core\.cjs"\);\r?\n\r?\n/;
if (!syncRequirePattern.test(source)) {
  throw new Error("main-source.cjs sync-core require block was not found.");
}

const bundled = source.replace(syncRequirePattern, () => `${coreForBundle}\n\n`);
if (bundled.includes('require("./sync-core.cjs")')) {
  throw new Error("Bundled main.js still contains a runtime sync-core require.");
}

fs.writeFileSync(
  outputPath,
  `// Generated by build.cjs. Edit main-source.cjs and sync-core.cjs, then run npm run build.\n${bundled}`,
);

console.log(`Built ${path.relative(process.cwd(), outputPath)}`);
